name: CLASP Push

on:
  pull_request:
    types: [closed]

jobs:
  clasp-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install CLASP
        run: npm install -g @google/clasp

      - name: Authenticate with Service Account
        run: echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" | base64 --decode > key.json && gcloud auth activate-service-account --key-file=key.json

      - name: Push to Apps Script
        run: clasp push
