name: CLASP Push

on:
  pull_request:
    types: [closed]

jobs:
  clasp-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install CLASP
        run: npm install -g @google/clasp

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Save tokens as secrets
        run:  |
            echo "GOOGLE_ACCESS_TOKEN=${{ steps.authenticate.outputs.access_token }}" >> $GITHUB_ENV
            echo "GOOGLE_ID_TOKEN=${{ steps.authenticate.outputs.id_token }}" >> $GITHUB_ENV
            echo "GOOGLE_REFRESH_TOKEN=${{ steps.authenticate.outputs.refresh_token }}" >> $GITHUB_ENV
          
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > credentials.json && export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json

      - name: Debug credentials
        run: cat credentials.json

      - name: CLASP push -f
        uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          clientId: ${{ secrets.GOOGLE_CLIENT_ID }}
          clientSecret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: 'push'
